exam_store/products/urls.py
from django.urls import path
from .views import ClothesCatalogue, ShoesCatalogue, AccessoriesCatalogue, CatalogueView, delete_product, \
    DetailProductView, add_product_view, edit_product_view,  add_to_cart, CheckoutView , remove_from_cart, order_thank_you

urlpatterns = (
    path("clothes/", ClothesCatalogue.as_view(), name="clothes_catalogue"),
    path("shoes/", ShoesCatalogue.as_view(), name="shoes_catalogue"),
    path("accessories/", AccessoriesCatalogue.as_view(), name="accessories_catalogue"),
    path('catalogue/', CatalogueView.as_view(), name='catalogue_page'),
    path('details/<int:pk>/', DetailProductView.as_view(), name='product_detail_page'),
    path('delete/<int:pk>/', delete_product, name='product_delete_page'),
    path('add/', add_product_view, name='product_add_page'),
    path('edit/<int:pk>/', edit_product_view, name='product_edit_page'),
    path('add-to-cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('remove_from_cart/<int:cart_item_id>/', remove_from_cart, name='remove_from_cart'),
    path('order/',order_thank_you, name= 'order_thank_you'),

)

exam_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('exam_store.auth_app.urls')),
    path('', include('exam_store.main.urls')),
    path('products/', include('exam_store.products.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

exam_store/products/models.py
from django.db import models

# Create your models here.

exam_store/products/forms.py
from django import forms

from exam_store.main.models import ProductModel


class ProductModelForm(forms.ModelForm):
    class Meta:
        model = ProductModel
        fields = '__all__'


class DeleteProductForm(forms.ModelForm):
    class Meta:
        model = ProductModel
        fields = []


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = ProductModel
        fields = ['name', 'description', 'price', 'image', 'category', 'quantity']


class CheckoutForm(forms.Form):
    full_name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=100)
    city = forms.CharField(max_length=100)
    address = forms.CharField(max_length=100)
    payment_method = forms.ChoiceField(choices=
    [
        ('credit_card', 'Credit Card'),
        ('paypal', 'PayPal'),
        ('bank_transfer', 'Bank Transfer'),
        ('on_delivery', 'On delivery')
    ]
    )

exam_store/products/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic import TemplateView, FormView, UpdateView, \
    DeleteView, DetailView
from django.conf import settings

from exam_store.auth_app.models import UserProfile
from exam_store.main.models import ProductModel, Cart
from django.contrib.auth.decorators import user_passes_test

from exam_store.products.forms import ProductModelForm, DeleteProductForm, ProductEditForm, CheckoutForm
from exam_store.main.models import ProductModel, CartItem


def add_to_cart(request, product_id):
    product = get_object_or_404(ProductModel, pk=product_id)

    cart, created = Cart.objects.get_or_create(user=request.user)
    user = request.user
    cart_item, item_created = CartItem.objects.get_or_create(cart=cart, product=product)

    if not item_created:
        cart_item.quantity += 1  # !!!!
        cart_item.save()

    return redirect('shopping_cart')  # Redirect to the product detail page


def add_product_view(request):
    if request.method == 'POST':
        form = ProductModelForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home_page')  # Redirect to home page after adding a product
    else:
        form = ProductModelForm()

    context = {}
    if request.user.is_authenticated:
        profile = UserProfile.objects.filter(pk=request.user.pk).first()
        context['profile'] = profile

    context['form'] = form
    return render(request, 'products/add_product.html', context)


def edit_product_view(request, pk):
    product = get_object_or_404(ProductModel, pk=pk)

    if request.method == 'POST':
        form = ProductEditForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect('home_page')  # Redirect to home page after editing the product
    else:
        form = ProductEditForm(instance=product)

    context = {'form': form, 'product': product}
    return render(request, 'products/edit_product.html', context)


def delete_product(request, pk):
    product = get_object_or_404(ProductModel, pk=pk)

    if request.method == 'POST':
        form = DeleteProductForm(request.POST, instance=product)
        if form.is_valid():
            product.delete()
            return redirect('home_page')  # Redirect to home page after deletion
    else:
        form = DeleteProductForm(instance=product)

    return render(request, 'products/delete_product.html', {'form': form, 'product': product})


class DetailProductView(DetailView, LoginRequiredMixin):
    template_name = 'products/details_product.html'
    model = ProductModel
    context_object_name = 'product'
    shoes = ProductModel.objects.filter(category="shoes")
    clothes = ProductModel.objects.filter(category="clothes")
    accessories = ProductModel.objects.filter(category="accessories")
    extra_context = {
        'shoes': shoes,
        'clothes': clothes,
        'accessories': accessories,
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Assuming you want to pass the logged-in user's profile to the context
        if self.request.user.is_authenticated:
            profile = UserProfile.objects.filter(pk=self.request.user.pk).first()
            context['profile'] = profile

        return context


class ClothesCatalogue(TemplateView, LoginRequiredMixin):
    template_name = "products/clothes_catalogue.html"
    clothes = ProductModel.objects.filter(category="clothes")
    extra_context = {
        'products': clothes
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Assuming you want to pass the logged-in user's profile to the context
        if self.request.user.is_authenticated:
            profile = UserProfile.objects.filter(pk=self.request.user.pk).first()
            context['profile'] = profile

        return context


class ShoesCatalogue(TemplateView, LoginRequiredMixin):
    template_name = "products/shoes_catalogue.html"
    shoes = ProductModel.objects.filter(category="shoes")
    extra_context = {
        'products': shoes
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Assuming you want to pass the logged-in user's profile to the context
        if self.request.user.is_authenticated:
            profile = UserProfile.objects.filter(pk=self.request.user.pk).first()
            context['profile'] = profile

        return context


class AccessoriesCatalogue(TemplateView, LoginRequiredMixin):
    template_name = "products/accessories_catalogue.html"
    accessories = ProductModel.objects.filter(category="accessories")
    extra_context = {
        'products': accessories
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Assuming you want to pass the logged-in user's profile to the context
        if self.request.user.is_authenticated:
            profile = UserProfile.objects.filter(pk=self.request.user.pk).first()
            context['profile'] = profile

        return context


class CatalogueView(TemplateView, LoginRequiredMixin):
    template_name = 'products/catalogue_page.html'
    model = ProductModel
    products = ProductModel.objects.all()
    extra_context = {
        "products": products,
    }

    def get(self, request, *args, **kwargs):
        products = ProductModel.objects.all()
        current_user = self.request.user
        context = {
            "products": products,
            "profile": current_user,
            "pk": current_user.id
        }
        return render(request, template_name='products/catalogue_page.html', context=context)


class CheckoutView(FormView):
    template_name = 'products/checkout_page.html'
    form_class = CheckoutForm
    success_url = reverse_lazy('order_thank_you')

    def form_valid(self, form):
        full_name = form.cleaned_data['full_name']
        email = form.cleaned_data['email']
        city = form.cleaned_data['city']
        address = form.cleaned_data['address']
        payment_method = form.cleaned_data['payment_method']

        message = render_to_string('email/order_confirmation_email.txt',
                                   {'full_name': full_name, 'email': email, 'city': city, 'address': address,
                                    'payment_method': payment_method})

        # Send email
        send_mail(
            'Order Confirmation',  # Subject
            message,  # Message
            settings.EMAIL_HOST_USER,  # From email
            [email],  # To email
            fail_silently=False,
        )

        # Further processing or redirecting logic
        return super().form_valid(form)

    def get_success_url(self):
        return self.success_url


def remove_from_cart(request, cart_item_id):
    cart_item = get_object_or_404(CartItem, pk=cart_item_id)
    cart_item.delete()
    return redirect('shopping_cart')


def order_thank_you(request):
    return render(request=request, template_name='products/order_thank_you.html')

templates/products/accessories_catalogue.html
{% extends 'main/base/base.html' %}
{% block content %}
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
        <meta name="description" content=""/>
        <meta name="author" content=""/>
        <title>Shop Homepage - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="/static/assets/favicon.ico"/>
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"/>
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/static/styles/styles.css" rel="stylesheet"/>
    </head>
    <body>

    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Shop in style</h1>
                <p class="lead fw-normal text-white-50 mb-0">With the best online store</p>
            </div>
        </div>
    </header>
    <!-- Section-->
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                {% for product in products %}
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->
                        <img class="card-img-top" src="{{ product.image.url }}" style="height: 240px ; width: 270px">
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">{{ product.name }}</h5>
                                <!-- Product price-->
                                <h5>{{ product.price }}$</h5>
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'product_detail_page' product.pk %}">View options</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    </body>
{% endblock %}

templates/products/add_product.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Add Product</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
          integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP"
          crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/add-product-style.css' %}">
</head>
<body>
<div class="container h-100">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card mt-5">
            <div class="d-flex justify-content-center">
                <h3 id="form-title">ADD PRODUCT</h3>
            </div>
            <div class="d-flex justify-content-center form_container">
                <form method="POST" action="{% url 'product_add_page' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.errors }}
                    {# Name #}
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-signature"><placeholder> Name</placeholder></i></span>
                        </div>
                        {{ form.name }}
                    </div>
                    {# Description #}
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-info-circle"><placeholder> Description</placeholder></i></span>
                        </div>
                        {{ form.description }}
                    </div>
                    {# Price #}
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-money-bill"><placeholder> Price</placeholder></i></span>
                        </div>
                        {{ form.price }}
                    </div>
                    {# Category #}
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-tag"><placeholder> Category</placeholder></i></span>
                        </div>
                        {{ form.category }}
                    </div>
                    {# Quantity #}
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-sort-amount-up-alt"><placeholder> Quantity</placeholder></i></span>
                        </div>
                        {{ form.quantity }}
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-image"><placeholder> Image</placeholder></i></span>
                            {{ form.image }}
                        </div>
                    </div>
                    <div class="d-flex justify-content-center mt-3 login_container">
                        <button type="submit" name="button" class="btn login_btn">Add</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/products/catalogue_page.html
{% extends 'main/base/base.html' %}
{% block content %}
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
        <meta name="description" content=""/>
        <meta name="author" content=""/>
        <title>Shop Homepage - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="/static/assets/favicon.ico"/>
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"/>
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/static/styles/styles.css" rel="stylesheet"/>
    </head>
    <body>

    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Shop in style</h1>
                <p class="lead fw-normal text-white-50 mb-0">With the best online store</p>
            </div>
        </div>
    </header>
    <!-- Section-->
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                {% for product in products %}
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->
                        <img class="card-img-top" src="{{ product.image.url }}" style="height: 240px ; width: 270px">
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">{{ product.name }}</h5>
                                <!-- Product price-->
                                <h5>{{ product.price }}$</h5>
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'product_detail_page' product.pk %}">View options</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    </body>
{% endblock %}

templates/products/checkout_page.html
<!-- checkout_page.html -->
{% extends 'main/base/base.html' %}
{% load static %}
<head>
    <title>Checkout Page</title>
    <link rel="stylesheet" href="{% static '/styles/checkout.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>

{% block content %}
    <hr style="padding: 30px">
    <div class="container mt-5">
        <h2 class="text-center mb-4">Checkout Page</h2>
        <form method="post" action="{% url 'checkout' %}" class="needs-validation d-flex justify-content-center" novalidate>
            {% csrf_token %}

            <div class="mb-3">
                <label for="id_full_name" class="form-label">
                    <i class="bi bi-person"></i>
                    Full Name
                </label>
                {{ form.full_name }}
                <div class="invalid-feedback">
                    Please enter your full name.
                </div>
            </div>

            <div class="mb-3">
                <label for="id_email" class="form-label">
                    <i class="bi bi-envelope"></i>
                    Email
                </label>
                {{ form.email }}
                <div class="invalid-feedback">
                    Please enter a valid email address.
                </div>
            </div>

            <div class="mb-3">
                <label for="id_city" class="form-label">
                    <i class="bi bi-house"></i>
                    City
                </label>
                {{ form.city }}
                <div class="invalid-feedback">
                    Please enter your city.
                </div>
            </div>

            <div class="mb-3">
                <label for="id_address" class="form-label">
                    <i class="bi bi-house-door"></i>
                    Address
                </label>
                {{ form.address }}
                <div class="invalid-feedback">
                    Please enter your address.
                </div>
            </div>

            <div class="mb-3">
                <label for="id_payment_method" class="form-label">
                    <i class="bi bi-credit-card"></i>
                    Payment Method
                </label>
                {{ form.payment_method }}
                <div class="invalid-feedback">
                    Please select a payment method.
                </div>
            </div>
            <!-- Add other form fields as needed -->

            <button type="submit" class="btn btn-primary btn-lg">Submit Order</button>
        </form>
    </div>
    <br>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
{% endblock %}

templates/products/clothes_catalogue.html
{% extends 'main/base/base.html' %}
{% block content %}
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
        <meta name="description" content=""/>
        <meta name="author" content=""/>
        <title>Shop Homepage - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="/static/assets/favicon.ico"/>
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"/>
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/static/styles/styles.css" rel="stylesheet"/>
    </head>
    <body>

    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Shop in style</h1>
                <p class="lead fw-normal text-white-50 mb-0">With the best online store</p>
            </div>
        </div>
    </header>
    <!-- Section-->
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                {% for product in products %}
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->
                        <img class="card-img-top" src="{{ product.image.url }}" style="height: 240px ; width: 266px">
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">{{ product.name }}</h5>
                                <!-- Product price-->
                                <h5>{{ product.price }}$</h5>
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'product_detail_page' product.pk %}">View options</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    </body>
{% endblock %}

templates/products/delete_product.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Delete Product</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous">
    <style>
        /* Add your custom styling here */
        body {
            background-color: #f0f0f0;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        .delete-card {
            width: 400px;
            padding: 20px;
            background-color: #333;
            color: white;
            border-radius: 10px;
            box-shadow: 0 10px 20px rgba(0, 0, 0, 0.2);
        }

        .delete-card h1 {
            font-size: 24px;
            margin-bottom: 10px;
        }

        .delete-card p {
            margin-bottom: 20px;
        }

        .form-group {
            margin-bottom: 20px;
        }

        .form-group label {
            color: white;
            font-weight: bold;
        }

        .form-group input {
            border: none;
            background-color: #464646;
            color: white;
            padding: 8px;
            border-radius: 5px;
            width: 100%;
        }

        .form-group input::placeholder {
            color: rgba(255, 255, 255, 0.5);
        }

        .form-group button {
            background-color: #ff4646;
            color: white;
            border: none;
            padding: 8px 20px;
            border-radius: 5px;
            cursor: pointer;
        }

        .form-group button:hover {
            background-color: #e03030;
        }

        .cancel-link {
            color: white;
            text-decoration: none;
        }

        .form-group button {
            background-color: #ff4646;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
            transition: background-color 0.3s ease-in-out;
        }

        .form-group button:hover {
            background-color: #e03030;
        }
    </style>
</head>
<body>
<div class="delete-card">
    <h1>Delete Product</h1>
    <p>Are you sure you want to delete "{{ product.name }}"?</p>

    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.product }}
        </div>
        <div class="form-group">
            {{ form.confirm }}
        </div>
        <button class="form-group" type="submit">Delete</button>
    </form>
    <a class="cancel-link" href="{% url 'home_page' %}">Cancel</a>
</div>
</body>
</html>

templates/products/details_product.html
{% extends 'main/base/base.html' %}
{% block content %}

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
        <meta name="description" content=""/>
        <meta name="author" content=""/>
        <title>Shop Item - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="/static/assets/favicon.ico"/>
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"/>
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/static/styles/styles.css" rel="stylesheet"/>
    </head>
    <style>
        .navbar-spacing {
            height: 50px; /* Adjust the height as needed */
        }

        .custom-text {
            white-space: pre-line;
        }

        .resized-image {
            width: 270px;
            height: auto;
            max-height: 240px
        }


    </style>
    <body>
    <div class="navbar-spacing"></div>
    <section class="py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="row gx-4 gx-lg-5 align-items-center">
                <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0"
                                           src="{{ product.image.url }}"/></div>
                <div class="col-md-6">
                    <h1 class="display-5 fw-bolder">{{ product.name }}</h1>
                    <div class="fs-5 mb-5">
                        <span>${{ product.price }}.00</span>
                    </div>
                    <p class="lead custom-text">{{ product.description }}</p>
                    <div class="d-flex">
                        <input class="form-control text-center me-3" id="inputQuantity" type="num" value="1"
                               style="max-width: 3rem"/>
                        <button class="btn btn-outline-dark flex-shrink-0" type="button"
                                onclick="location.href='{% url 'add_to_cart' product.pk %}'">
                            <i class="bi-cart-fill me-1"></i>
                            Add to cart
                        </button>
                        {% if profile.is_staff or profile.is_admin %}
                        <a href="{% url 'product_edit_page' product.id %}" class="btn btn-outline-dark flex-shrink-0">
                            <i class="bi-pencil-fill me-1" style="font-size: 1.25rem;"></i>
                            Edit
                        </a>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="py-5 bg-light">
        <div class="container px-4 px-lg-5 mt-5">
            <h2 class="fw-bolder mb-4">Related products</h2>
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                {% for shoe in shoes %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top resized-image" src="{{ shoe.image.url }}"/>
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ shoe.name }}</h5>
                                    <!-- Product price-->
                                    ${{ shoe.price }}.00
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto"
                                                            href="{% url 'product_detail_page' shoe.pk %}">View
                                    options</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    </body>
    </html>
{% endblock %}